--QUERY1--
SELECT EXTRACT(YEAR from C.COLLISION_DATE) as YEAR, COUNT(*) as NUMBER_COLLISIONS from COLLISIONS C
group by EXTRACT(YEAR from C.COLLISION_DATE);

--QUERY2 (Probablement fausse, pas sûr du max sur count(*)-- 
SELECT P.VEHICLE_MAKE, MAX(COUNT(*)) as NUMBER_VEHICLE from PARTIES P
group by P.VEHICLE_MAKE;

--QUERY3--
SELECT COUNT(*)/(SELECT COUNT(*) from CONDITION) as FRACTION_DARK from CONDITION COND
WHERE COND.LIGHTING_ID IN
(SELECT L.ID from LIGHTING L
where LOWER(L.DEFINITION) LIKE '%dark%');

--QUERY4--
SELECT COUNT(*) as NUMBER_COLLISIONS_SNOWY_WEATHER from CONDITION_WITH_WEATHER CWW
where WHEATHER_ID in
(SELECT W.ID from WEATHER W
where LOWER(W.DEFINITION) LIKE '%snow%');

--QUERY5--
-- QUESTION: Many post on stackoverflow say to use DATENAME func or DATE_FORMAT but
-- it doesn't seem available here. What to do?

--QUERY6--
SELECT W.DEFINITION, COUNT(*) as NUMBER_COLLISIONS from WEATHER W, CONDITION_WITH_WEATHER CWW
WHERE W.ID=CWW.WHEATHER_ID
group by W.DEFINITION --OR GROUPBY CWW.WHEATHER_ID MAYBE, SHOULD BE THE SAME
ORDER BY COUNT(*) DESC;
