--QUERY 3
SELECT P.VEHICLE_MAKE, COUNT(*) AS NUMBER_OF_VICTIMS_KILLER_OR_WITH_SEVERE_INJURIES from PARTIES P
WHERE P.ID In
(SELECT V.ID from VICTIMS V
where V.VICTIM_DEGREE_OF_INJURY_ID in
(SELECT VDOI.ID from VICTIM_DEGREE_OF_INJURY VDOI
where (LOWER(VDOI.DEFINITION) LIKE '%killed%' OR LOWER(VDOI.DEFINITION) LIKE '%severe injury%')))
and P.VEHICLE_MAKE is not NULL -- NULL is the 4th more represented, not really interesting
group by P.VEHICLE_MAKE
order by  COUNT(*) DESC
FETCH FIRST 10 ROW ONLY;
